name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build LaTeX files using devcontainer
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}
        cacheFrom: ghcr.io/${{ github.repository }}
        runCmd: make
    - name: Archive documents
      uses: actions/upload-artifact@v4
      with:
        name: questionnaire
        path: out/questionnaire.pdf
